export const teamContent = {
  hero: {
    label: "Our Team",
    title: "Practitioners who deploy at scale",
    subtitle:
      "Engineers, architects, and program leaders who have delivered complex AI and infrastructure systems for institutional environments.",
  },
  credibilityMetrics: [
    { label: "AWS-scale infrastructure", value: "Enterprise" },
    { label: "Catalog assets", value: "60M+" },
    { label: "Ingestion throughput", value: "50K TPS" },
    { label: "Governed PII records", value: "100M+" },
    { label: "Program delivery", value: "$15M+" },
    { label: "Digital twin systems", value: "Multi-sector" },
    { label: "AI security architecture", value: "Production-grade" },
    { label: "Smart infrastructure", value: "Deployed" },
  ],
  members: [
    {
      id: "praveen-ashok-kumar",
      name: "Praveen Ashok Kumar",
      role: "Senior Technical Program Manager",
      bio: "10+ years delivering IoT, AI, and large-scale software systems. Leads digital twin programs, smart infrastructure, and government-scale technology delivery.",
      expertise: ["IoT", "AI/ML", "Digital Twins", "Cloud Architecture", "Smart Infrastructure"],
      linkedin: "https://www.linkedin.com/in/praveenashok",
      photo: "/images/team/praveen.jpg",
      initials: "PA",
    },
    {
      id: "prathipa-ashok-kumar",
      name: "Prathipa Ashok Kumar",
      role: "Business & Strategy Lead",
      bio: "Drives institutional partnerships, program scale, and cross-functional delivery across government and enterprise technology engagements.",
      expertise: ["Institutional Strategy", "Program Delivery", "Operations", "Partnerships", "Growth"],
      linkedin: "https://www.linkedin.com/in/prathipa-ashok",
      photo: "/images/team/prathipa.jpg",
      initials: "PA",
    },
    {
      id: "udhgee-murugesan",
      name: "Udhgee Murugesan",
      role: "AI Security Engineer",
      bio: "A decade of AI/ML security experience building production-grade secure architectures and mitigating advanced threats in large-scale systems.",
      expertise: ["AI Security", "Threat Modeling", "Cloud Security", "Secure Deployment", "AWS"],
      linkedin: "https://www.linkedin.com/in/udhgee",
      photo: "/images/team/udhgee.jpg",
      initials: "UM",
    },
    {
      id: "raghavan-kothandaraman",
      name: "Raghavan Kothandaraman",
      role: "Senior Software Engineer",
      bio: "Distributed systems engineer building high-performance platforms handling millions of assets and real-time data pipelines at institutional scale.",
      expertise: ["Distributed Systems", "AWS", "High Throughput", "System Design", "Data Platforms"],
      linkedin: "https://www.linkedin.com/in/raghavankothandaraman",
      photo: "/images/team/raghavan.jpg",
      initials: "RK",
    },
    {
      id: "priyanka-praveen",
      name: "Priyanka Praveen",
      role: "Architect & Design Specialist",
      bio: "Designs user-centric systems and environments — bridging physical infrastructure thinking with digital product experience.",
      expertise: ["Systems Design", "UX Architecture", "Spatial Design", "Accessibility", "Product Design"],
      linkedin: "https://www.linkedin.com/in/ar-priyanka-praveen-8bb34418a",
      photo: "/images/team/priyanka.jpg",
      initials: "PP",
    },
    {
      id: "anchana-m",
      name: "Anchana",
      role: "AI & Full Stack Developer",
      bio: "Builds applied AI and full-stack applications including detection systems, accessibility tools, and operational platforms.",
      expertise: ["Python", "AI/ML", "Full Stack", "Multimodal AI", "Application Development"],
      linkedin: "https://www.linkedin.com/in/anchana-mariselvam/",
      photo: "/images/team/anchana.jpg",
      initials: "AM",
    },
  ],
  mission: {
    label: "Why We Build",
    title: "One team. Deployment-grade standard.",
    body: "Phaarvai was built by practitioners who have delivered complex technology at scale — not advisors who stop at recommendations. Every team member owns outcomes end to end, from architecture through deployment. Institutions that serve the public deserve systems built to the same standard as the best enterprise technology.",
  },
};
